# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc11c75c1ce00b017d80ecf46a6a14109836cc7e44bf0c350f5682735c6535af7c0fc85e3924fb7bbaf98462d6f6f5915770f4e15909af1489249f0e13ff2b3

test:
  secret_key_base: 777abe025d206445596dff8826821c825c7322e92233fe79cb0041d58493168bd5f24429687415ad27e35c899ac47b2ae592c20f91ff5e0ab1218f2e53f0df87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
